use_frameworks!

platform :ios, '10.0'

target 'UIAlertControllerBuilder_Example' do
  pod 'UIAlertControllerBuilder', :path => '../'

  target 'UIAlertControllerBuilder_Tests' do
    inherit! :search_paths

    
  end
end
